### ISSUE TITLE
image looks blocky on zsh on konsole, it also adds stuff to input

### ISSUE THREAD

**Issue by Akane-Kurokawa-1** [sech1p/blahaj#1]
I tried it on Konsole using zsh and it looks blocky, and inserts `62;1;4c` into the **input**, on bash it sometimes works perfectly but usually looks the same  
on kitty it looks normal but still adds to the **input** `Gi=31;OK`

zsh in konsole:  
[Screencast_20240913_143604.webm](https://github.com/user-attachments/assets/c7e9d5ce-df12-4d66-9e60-06e622ec7b65)

bash in konsole(usually):  
[Screencast_20240913_144335.webm](https://github.com/user-attachments/assets/5b8b2831-44b0-4430-a9b7-175237927ab4)

kitty(both zsh and bash are the same):  
[Screencast_20240913_145017.webm](https://github.com/user-attachments/assets/22cb1d24-e60a-4e9f-98ea-ca8a6ea94174)

I'm running manjaro kde, installed blahaj from the AUR  
my versions:  
```
$ blahaj --version
0.2.2
$ zsh --version 
zsh 5.9 (x86_64-pc-linux-gnu)
$ bash --version
GNU bash, version 5.2.32(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ konsole --version 
konsole 24.05.2
$ viu --version 
viu 1.5.0
$ node --version
v22.7.0
$ kitty --version   
kitty 0.36.1 created by Kovid Goyal
```
my .zshrc:  
```bash
# Use powerline
USE_POWERLINE="true"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  source /usr/share/zsh/manjaro-zsh-prompt
fi
alias ll='ls -lh'
alias la='ls -A'
alias lla='ls -Alh'
```

**Comment by d34dinsid3k1tty** [comment]
Hi! Thank you for your issue :3

I'm trying resolve what's happened, right now. I will resolve what's happened that not working as I excepted and I will send updates as soon as possible

Greetings,
Eliza

**Comment by d34dinsid3k1tty** [comment]
Also, can you provide your `$TERM` and `$LC_ALL` + `$LANG` variables? It's `xterm-256color`, "" and `en_US.UTF-8` for me. And you can show how are [this image](https://www.ikea.com/pl/pl/images/products/blahaj-pluszak-rekin__0710175_pe727378_s5.jpg) looks on your configurations using `viu`? Thanks

**Comment by Akane-Kurokawa-1** [comment]
my vars on konsole:
```
$ echo -e $TERM\\n$LC_ALL\\n$LANG
xterm-256color

en_US.UTF-8
```
so the same
here's using viu (looks normal): 
![Screenshot_20240913_163325](https://github.com/user-attachments/assets/30a836a4-b3fc-41b9-8985-4554a1e4ec48)

**Comment by d34dinsid3k1tty** [comment]
Okay, thank you, I'm going to resolve this. I will ask if I will have question

**Comment by Akane-Kurokawa-1** [comment]
okie, btw running `spawn("viu", ["blahaj-pluszak-rekin__0710175_pe727378_s5.jpg"], { stdio: "inherit" });` on its own works fine

**Comment by d34dinsid3k1tty** [comment]
Yeah, thank you for telling me, for me it working normally too in my setup but still don't know what something went wrong here...

**Comment by d34dinsid3k1tty** [comment]
Can you tried install it from source? Like building and then invoke `sudo npm install -g .` ?

**Comment by Akane-Kurokawa-1** [comment]
yeah, I tried and it's the same, I actually found the issue, will send a pull request
